---
title: "Database importation and modifications"
output: html_document
author : "Nina Prasil & Jeremy Wicquart"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: "cosmo"
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, fig.align = "center")

```

# Defining functions and packages

```{r base}

# 1. Source functions ----

source("functions/graphical_par.R")
source("functions/theme_graph.R")

# 2. Required packages ----

library(tidyverse) # Core tidyverse packages
library(sf) # To plot maps
library(formattable) # For interactive html tables
library(DT) # For interactive html tables

# 3. Set default ggplot theme ----

theme_set(theme_graph())

```

# 1. Reef area by country

```{r}

# 1. Load data ----

load(file = "./../data/reefs.eez.Rdata")

# 2. Transform to an sf object ----

data_reefs <- reefs.eez %>% 
  st_as_sf()

# 3. Calculate the reef area by country ----

data_reefs <- data_reefs %>% 
  # Calculate the reef area and transform it from m2 to km2
  mutate(reef_area = as.numeric(st_area(.))/1000000) %>%
  # Make the sum of area by country
  st_drop_geometry() %>% 
  group_by(SOVEREIGN1) %>% 
  summarise(total_area_abs = sum(reef_area)) %>% 
  ungroup() %>% 
  # Sort rows from higher reef area to lower
  arrange(-total_area_abs) %>% 
  # Calculate the relative contribution
  mutate(total_area_rel = total_area_abs*100/sum(total_area_abs),
         pos = row_number()) %>% 
  # Misc. modifications for formattable
  select(pos, SOVEREIGN1, total_area_abs, total_area_rel) %>% 
  mutate(total_area_abs = round(as.numeric(total_area_abs), 3),
         total_area_rel = round(as.numeric(total_area_rel), 3))

# 4. Make the table ----

#data_reefs %>% 
#  formattable(.) %>% 
#  as.datatable(., rownames = FALSE, colnames = c("N°", "Country", "Area (km²)", "Relative (%)"))

```

# 2. Economic Exclusive Zone

```{r}

# 1. Load EEZ data ----

data_eez <- read_sf("../data/01_maps/World_EEZ_v11_20191118/eez_v11.shp") %>% 
  select(SOVEREIGN1)

# 2. Make the map ----

#ggplot() +
#  geom_sf(data = data_eez)

```

# 3. Defining top 30

```{r}

# Import database 
data_benthos <- read.csv2("./../data/03-merge_all_all_all_benthos_NA.csv") 

#Converts the coordinates in the database in an sf object

data_benthos_join <- data_benthos %>% 
  # Remove non-filled? sites location
  filter(!is.na(Latitude) & !is.na(Longitude) & !is.na(Year)) %>%
  # Set as sf object
   st_as_sf(., coords = c("Longitude", "Latitude")) 

# Add a CRS to the database (CRS = GWS84, ESPG = 4326)
st_crs(data_benthos_join) <- 4326

# Join the location sites to the EEZs to get the real names $SOVEREIGN1
data_benthos_join <- st_join(data_benthos_join, data_eez)

# Get top 30 from data_reefs

top_30 <- data_reefs %>% 
  select(pos, SOVEREIGN1) %>% 
  slice(1:30) 

temp <- top_30$SOVEREIGN1

# Get top 30 from the database

data_benthos_30 <- data_benthos_join %>% 
  filter(SOVEREIGN1 %in% temp)

```

# 4. Adding time range (summarized dataset)

```{r}
# 1. Load data ----

#data_benthos <- read.csv2("./../data/03-merge_all_all_all_benthos_NA.csv") 

data_benthos_tRange <- data_benthos %>% 
  filter(!is.na(Latitude) & !is.na(Longitude) & !is.na(Year)) %>%
  group_by(Area, Country, Location, Site, Latitude, Longitude) %>% 
  summarise(interval_years = max(Year, na.rm = TRUE) - min(Year, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(interval_class = cut(interval_years, 
                              breaks = c(-Inf, 1, 5, 10, 20, Inf),
                              labels = c("1", "2-5", "6-10", "11-20", ">20")))



```


# 5. Save objects as RData

```{r}

save(data_benthos_30, 
     file = "./../data/00_filtered/00-data_benthos-top_30.RData")

save(data_benthos_tRange, 
     file = "./../data/00_filtered/00-data_benthos-time_range_monitoring.RData")

# POssibility to combine both :
# save(dta_benthos_30, data_benthos_tRange, file = "./../data/00_filtered/00-data_benthos-filtered.RData")

# Test
#load("./../data/00_filtered/00-data_benthos-top_30.RData")
```