---
title: "Database importation and modifications"
output: html_document
author : "Nina Prasil & Jeremy Wicquart"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: "cosmo"
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, fig.align = "center")

```

# Defining functions and packages

```{r base}

# 1. Required packages ----

library(tidyverse) # Core tidyverse packages
library(sf) # To plot maps
sf_use_s2(FALSE) # Switch from S2 to GEOS
library(rgdal) # To open shapefile

```

# 1. Reef area by country

```{r}

# 1. Load and transform EEZ data ----

data_eez <- read_sf("../data/01_maps/World_EEZ_v11_20191118/eez_v11.shp") %>% 
  select(SOVEREIGN1, TERRITORY1) %>% 
  mutate(SOVEREIGN1 = case_when(TERRITORY1 == "Glorioso Islands" ~ "France",
                                TERRITORY1 == "Chagos Archipelago" ~ "United Kingdom",
                                TRUE ~ SOVEREIGN1)) %>% 
  st_wrap_dateline() %>% 
  st_transform(., crs = 4326)

# 2. Load and transform reef area data (from Reefs at Risk, 2011) ----

data_rar <- read_sf("../data/02_reefs-at-risk_reef-data/reef_500_poly.shp") %>% 
  st_transform(., crs = 4326) %>% 
  st_wrap_dateline() %>% 
  st_transform(., crs = 32663) %>% 
  st_cast("POLYGON") %>% 
  mutate(AREA = st_area(.)) %>% 
  st_transform(., crs = 4326)

# 3. Join the data ----

data_eez_joined <- st_intersection(data_rar, data_eez)

```


```{r}

# 1. Load data_eez_joined (result from previous R chunk) ----

load("../data/data_eez_joined.RData")

# 2. Load ecoregions from Veron et al, 2015 to extract the specific CRS ----

load("../data/TEST/ecoregions.RData")

# 2. Load and transform data from Reefs at Risk, 2011 ----

data_eez_joined <- data_eez_joined  %>% 
  st_transform(crs = st_crs(ecoregions)) %>% 
  st_make_valid() %>% 
  mutate(area_ctry = st_area(.)) %>% 
  st_drop_geometry() %>% 
  group_by(SOVEREIGN1) %>% 
  summarise(total_area_abs = sum(area_ctry)) %>% 
  ungroup() %>% 
  drop_na(SOVEREIGN1) %>% #○ Doing so I remove a small portion of unassigned reef surface
  # Convert from m² to km²
  mutate(total_area_abs = as.numeric(total_area_abs)/10^6) %>% 
  # Sort rows from higher reef area to lower
  arrange(-total_area_abs) %>% 
  # Calculate the relative contribution
  mutate(total_area_rel = total_area_abs*100/sum(total_area_abs),
         pos = row_number()) %>% 
  # Re-order variables
  select(pos, SOVEREIGN1, total_area_abs, total_area_rel) 

sum(data_eez_joined$total_area_abs)


```















# Test wkt crs murray


```{r}


ggplot() +
  geom_sf(data = ecoregions, aes(fill = Ecoregion), show.legend = FALSE)

st_crs(ecoregions)

```

```{r}

data_rar <- read_sf("../data/02_reefs-at-risk_reef-data/reef_500_poly.shp")  %>% 
  st_transform(crs = st_crs(ecoregions))

st_area(data_rar)/10^6

```


# 1.1 Join EEZ and reef area

```{r}

# 1. Load and transform EEZ data ----

data_eez <- read_sf("../data/01_maps/World_EEZ_v11_20191118/eez_v11.shp") %>% 
  select(SOVEREIGN1, TERRITORY1) %>% 
  mutate(SOVEREIGN1 = case_when(TERRITORY1 == "Glorioso Islands" ~ "France",
                                TERRITORY1 == "Chagos Archipelago" ~ "United Kingdom",
                                TRUE ~ SOVEREIGN1)) %>% 
  st_wrap_dateline() %>% 
  st_transform(., crs = 4326)

# 2. Load and transform reef area data (from Reefs at Risk, 2011) ----

data_rar <- read_sf("../data/02_reefs-at-risk_reef-data/reef_500_poly.shp") %>% 
  st_transform(., crs = 4326) %>% 
  st_wrap_dateline() %>% 
  st_transform(., crs = 32663) %>% 
  st_cast("POLYGON") %>% 
  mutate(AREA = st_area(.)) %>% 
  st_transform(., crs = 4326)

# 3. Join the data ----

data_eez_joined <- st_intersection(data_rar, data_eez)

# 4. Save the data ----

save(data_eez_joined, file = "../data/data_eez_joined.RData")

# 5. Remove useless objects ----

rm(data_eez, data_rar, data_eez_joined)

```

# 1.2 Calculation of reef area

```{r}

# 1. Load the data ----

load("../data/data_eez_joined.RData")

# 2. Make the calculations ----

data_reefs <- data_eez_joined %>% 
  st_transform(., crs = 32663) %>% 
  st_make_valid() %>% 
  mutate(area_ctry = st_area(.)) %>% 
  st_drop_geometry() %>% 
  group_by(SOVEREIGN1) %>% 
  summarise(total_area_abs = sum(area_ctry)) %>% 
  ungroup() %>% 
  #♠ Convert from m² to km²
  mutate(total_area_abs = as.numeric(total_area_abs)/10^6) %>% 
  # Sort rows from higher reef area to lower
  arrange(-total_area_abs) %>% 
  # Calculate the relative contribution
  mutate(total_area_rel = total_area_abs*100/sum(total_area_abs),
         pos = row_number()) %>% 
  # Re-order variables
  select(pos, SOVEREIGN1, total_area_abs, total_area_rel)

```

```{r}

data_eez <- data_eez %>% 
  filter(SOVEREIGN1 %in% c("Egypt", "Sudan"))

ggplot() +
  geom_sf(data = data_eez, aes(fill = SOVEREIGN1))

data_rar_sect <- st_join(data_rar, data_eez, join = st_intersects) %>% 
    filter(SOVEREIGN1 %in% c("Egypt", "Sudan"))

ggplot() +
  geom_sf(data = data_rar_sect, aes(fill = SOVEREIGN1)) +
  geom_sf(data = data_eez, col = "red", fill = NA) +
  coord_sf(xlim = c(35, 38), ylim = c(23, 24))

data_rar_section <- st_intersection(data_rar, data_eez) %>% 
    filter(SOVEREIGN1 %in% c("Egypt", "Sudan"))

ggplot() +
  geom_sf(data = data_rar_section, aes(fill = SOVEREIGN1)) +
  geom_sf(data = data_eez, col = "red", fill = NA) +
  coord_sf(xlim = c(35, 38), ylim = c(23, 24))

```

```{r}

data_eez_test <- data_eez %>% 
  filter(SOVEREIGN1 %in% c("Sudan", "Egypt"))

data_eez_test_buf <- data_eez_test %>% 
  st_buffer(., dist = 0.5)


data_full <- st_sym_difference(data_eez_test, data_eez_test_buf)

ggplot() +
  geom_sf(data = data_full, alpha = 0.5, aes(fill = SOVEREIGN1))


data_full <- st_intersection(data_eez_test, data_eez_test_buf)

ggplot() +
    geom_sf(data = data_eez_test, alpha = 0.5, aes(fill = SOVEREIGN1)) +
  geom_sf(data = data_eez_test_buf, alpha = 0.5, aes(fill = SOVEREIGN1))


ggplot() +
  geom_sf(data = data_eez_test, alpha = 0.5, aes(fill = SOVEREIGN1)) +
  geom_sf(data = data_eez_test_buf, alpha = 0.5, aes(fill = SOVEREIGN1))




```


# 2. Economic Exclusive Zone

```{r}

# 1. Load EEZ data ----

data_eez <- read_sf("../data/01_maps/World_EEZ_v11_20191118/eez_v11.shp")

# 2. Change SOVEREIGN1 for Gloriosos islands from Madagascar to France ----

data_eez <- data_eez %>% 
  mutate(SOVEREIGN1 = case_when(TERRITORY1 == "Glorioso Islands" ~ "France",
                                TERRITORY1 == "Chagos Archipelago" ~ "United Kingdom",
                                TRUE ~ SOVEREIGN1))

```

# 3. Defining top 30

```{r}

# 1. Extract the top 30 countries in reef surface ----

top_30 <- data_reefs %>% 
  select(pos, SOVEREIGN1) %>% 
  slice(1:31) %>% 
  filter(SOVEREIGN1 != "Mauritius")

# 2. Extract benthic GCRMN data corresponding to the top 30 ---- 

data_benthos <- read.csv2("../data/03-merge_all_all_all_benthos_NA.csv") %>% 
  # Remove some datasets (those leading to bias)
  filter(!(DatasetID %in% c("XLCA1", "XLCA2", "XLCA3", "XLCA4", "XLCA5",
                            "PACN1.1", "PACN1.2", "PACN1.3", "PACN1.4",
                            "TIAH1", "RFCK1"))) %>% 
  # Remove NA
  drop_na(Latitude, Longitude, Year) %>%
  # Set as sf object
  st_as_sf(., coords = c("Longitude", "Latitude"), crs = 4326) %>% 
  # Join with EEZ
  st_join(., data_eez) %>% 
  # Extract top 30 countries in reef surface
  filter(SOVEREIGN1 %in% unique(top_30$SOVEREIGN1))

# 3. Save the data ----

save(data_benthos, file = "./../data/00_filtered/00-data_benthos-top_30.RData")

```

# 4. Defining time range (summarized dataset)

```{r}

# 1. Load data ----

data_benthos_range <- data_benthos %>% 
  mutate(Longitude = st_coordinates(.)[,"X"],
         Latitude = st_coordinates(.)[,"Y"]) %>% 
  st_drop_geometry() %>% 
  group_by(Area, Country, Location, Site, Latitude, Longitude, SOVEREIGN1) %>% 
  summarise(interval_years = max(Year, na.rm = TRUE) - min(Year, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(interval_class = cut(interval_years, 
                              breaks = c(-Inf, 1, 5, 10, 20, Inf),
                              labels = c("1", "2-5", "6-10", "11-20", ">20"))) %>% 
  st_as_sf(., coords = c("Longitude", "Latitude"))

# Add a CRS to the database (CRS = WGS84, ESPG = 4326)
st_crs(data_benthos_range) <- 4326

# Export to RData

save(data_benthos_range, 
     file = "./../data/00_filtered/00-data_benthos-time_range_monitoring.RData")

```

# 5. Bind background maps in one file

```{r}

# 1. Load the maps ----

# 1.1 Major islands --

land_major <- readOGR("./../data/01_maps/ne_10m_land/ne_10m_land.shp", "ne_10m_land") %>% 
  st_as_sf() %>% 
  mutate(scalerank = as.character(scalerank))

# 1.2 Minor islands --

land_minor <- readOGR("./../data/01_maps/ne_10m_minor_islands/ne_10m_minor_islands.shp", "ne_10m_minor_islands") %>% 
  st_as_sf()

# 1.3 Reefs data --

land_reefs <- readOGR("./../data/01_maps/ne_10m_reefs/ne_10m_reefs.shp", "ne_10m_reefs") %>% 
  st_as_sf()

# 2. Bind maps and save object ----

background_map <- bind_rows(land_reefs, land_minor) %>% 
  bind_rows(., land_major) %>% 
  st_as_sf(., crs = "+proj=longlat +datum=WGS84") 

# 3. Save the data ----

save(background_map, file = "./../data/01_maps/00_background_map.RData")

```
