---
title: "Analyses - MPA by country"
author : "Nina Prasil & Jeremy Wicquart"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: "cosmo"
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, fig.align = "center")

```

# Import functions, packages and data

```{r base}

source("functions/graphical_par.R")
source("functions/theme_map.R")


# 2. Required packages ----

library(tidyverse) # Core tidyverse packages
library(extrafont) # Font use
library(readxl) # To read excel files
library(sf) # To plot maps

# 3. Load data ----
# 3.1. MPAs from MPAtlas

data_mpa <- read_sf("./../data/02_mpa/mpatlas_20201223_clean/mpatlas_20201223_clean.shp") %>% 
  # Select top 30
  filter(sovereign %in% c("AUS", "IDN", "PHL", "FRA", "PNG", "USA", "FJI", "SLB", "SAU", "MDV",
                          "CUB", "FSM", "BHS", "MDG", "MHL", "IND", "MYS", "EGY", "KIR", "TZA",
                          "MOZ", "SDN", "ERI", "JPN", "SYC", "BLZ", "GBR", "VUT", "TON", "MEX")) %>% 
  # Homogenize countries names
  rename(SOVEREIGN1 = sovereign) %>% 
  filter(is_mpa == 1) %>% 
  mutate(SOVEREIGN1 = str_replace_all(SOVEREIGN1, 
                                      c("AUS" = "Australia",
                                        "BHS" = "Bahamas", 
                                        "BLZ" = "Belize",
                                        "CUB" = "Cuba", 
                                        "EGY" = "Egypt", 
                                        "ERI" = "Eritrea", 
                                        "FJI" = "Fiji", 
                                        "FRA" = "France", 
                                        "FSM" = "Federated States of Micronesia",
                                        "GBR" = "United Kingdom",
                                        "IDN" = "Indonesia", 
                                        "IND" = "India", 
                                        "JPN" = "Japan", 
                                        "KIR" = "Kiribati",
                                        "MDG" = "Madagascar", 
                                        "MDV" = "Maldives", 
                                        "MEX" = "Mexico",
                                        "MHL" = "Marshall Islands",
                                        "MOZ" = "Mozambique", 
                                        "MYS" = "Malaysia",
                                        "PHL" = "Philippines", 
                                        "PNG" = "Papua New Guinea",
                                        "SAU" = "Saudia Arabia",
                                        "SDN" = "Sudan", 
                                        "SLB" = "Solomon Islands",
                                        "SYC" = "Seychelles",
                                        "TON" = "Tonga",
                                        "TZA" = "Tanzania",
                                        "USA" = "United States",
                                        "VUT" = "Vanuatu")))

# 3.2 Coral distribution - CRS in meters

coral_distribution <- read.csv("./../data/01_maps/02-clean_coral-distribution-reef-at-risk-data.csv") %>% 
  st_as_sf(., coords = c("long", "lat"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

```

# Nb MPA zones with coral reefs

```{r}

# 1. Number of MPA zones  ----

data_mpa_top30 <- data_mpa %>% 
  group_by(SOVEREIGN1) %>% 
  st_drop_geometry() %>% 
  summarise(nb_mpa = n()) %>% 
  ungroup()



# 2. Extract all the MPA zones that contain coral reefs for the top 30 ----
# Does not take into account the protection level

mpa_w_reef <- data_mpa %>% 
  #spatial join btw coral distrib and the location of the MPAs
  st_join(coral_distribution, .,  left = FALSE) %>% 
  st_drop_geometry() %>% 
  #retain only one line per MPA
  distinct(mpa_id, .keep_all = T) %>% 
  group_by(SOVEREIGN1) %>% 
  summarise(nb_mpa_w_cr = n()) %>% 
  ungroup() %>% 
  arrange(SOVEREIGN1) %>% 
  left_join(data_mpa_top30, .)



```

# Surface MPA

```{r}

# 1. Calculate MPA area

mpa_area <- list()

for (i in unique(data_mpa$SOVEREIGN1)) {
  
  data_mpa_i <- data_mpa %>% 
    filter(SOVEREIGN1 == i) 
  
  mpa_comb_i <- st_union(st_combine(data_mpa_i), by_feature = T)
   
  mpa_area_i <- st_area(mpa_comb_i) 
  
  units(mpa_area_i) <- "km^2"
  
  mpa_area[[i]] = mpa_area_i
  
}

# 2. Clean table with all MPA related infos

mpa_table <- as.data.frame(mpa_area, row.names = T) %>% 
  pivot_longer(., "Australia":"Eritrea", names_to = "SOVEREIGN1", values_to = "mpa_area_km2") %>% 
  arrange(SOVEREIGN1) %>% 
  left_join(mpa_w_reef, .)


# 3. Save table 

write_csv2(mpa_table, "../figs/02_mpa-with-reef.csv")

```



# Reproducibility

```{r reprod}

# 1. Reproducibility ----

sessionInfo()

```

---
Nina PRASIL & Jeremy WICQUART | `r format(Sys.time())`